---
# main playbook to call roles

- name: Implement vdr scan sat and catv
  hosts: receiver1
  gather_facts: false
  roles:
    - vdr_scan
  vars:
    - cat_tv_freq_file: /usr/share/dvb/dvb-c/bg-Sprint
    - vdr_channels_conf_path: /var/lib/vdr/channels.conf
    - dvb_c_adapter_number: 1


